.TH "_MSQosAnalyser" 3 "18 Mar 2014" "Version 2.9.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MSQosAnalyser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bitratecontrol.h>\fP
.SH "Detailed Description"
.PP 
A MSQosAnalyzer is responsible to analyze RTCP feedback and suggest actions on bitrate or packet rate accordingly. This is an abstract interface. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code.
