.TH "_MSToneDetectorDef" 3 "18 Mar 2014" "Version 2.9.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MSToneDetectorDef \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mstonedetector.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfrequency\fP"
.br
.ti -1c
.RI "int \fBmin_duration\fP"
.br
.ti -1c
.RI "float \fBmin_amplitude\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure describing which tone is to be detected. 
.SH "Field Documentation"
.PP 
.SS "int \fB_MSToneDetectorDef::frequency\fP"Expected frequency of the tone 
.SS "int \fB_MSToneDetectorDef::min_duration\fP"Min duration of the tone in milliseconds 
.SS "float \fB_MSToneDetectorDef::min_amplitude\fP"Minimum amplitude of the tone, 1.0 corresponding to the normalized 0dbm level 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code.
