.TH "Audio filters" 3 "18 Mar 2014" "Version 2.9.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio filters \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fB- SILK (Skype codec)  plugin\fP"
.br
.PP

.RI "\fISILK Speech Codec (draft-vos-silk-02) plugins filters to encode and decode audio. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code.
