.TH "mediastreamer2_readme" 3 "18 Mar 2014" "Version 2.9.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mediastreamer2_readme \- README 
.PP
.nf
This directory contains a minimal version of oRTP containing only the generic
functionalities (logging, payload type definitions, b64...) that are mandatory
to be able to compile mediastreamer2 without the oRTP dependency
(configuration option --disable-ortp).

If some changes are made in oRTP they can be automatically synchronized here
thanks to the update_ortp.sh script.
.fi
.PP
 
